[colors]
light-red = "#bc5653"
light-yellow = "#ebc17a"
light-blue = "#7eaac7"
light-black = "#636363"
light-cyan = "#86d3ce"
light-white = "#f7f7f7"
light-green = "#909d63"
light-magenta = "#aa6292"
dim-background = "#202020"
light-background = "#3a3a3a"
dim-foreground = "#dbdbdb"
light-foreground = "#d9d9d9"
background = "#2c2c2c"
foreground = "#d6d6d6"
dim-blue = "#556b79"
dim-cyan = "#5c8482"
dim-magenta = "#6e4962"
dim-green = "#5e6547"
dim-white = "#828282"
dim-red = "#74423f"
dim-black = "#232323"
dim-yellow = "#8b7653"
cursor = "#d9d9d9"
text = "#2c2c2c"
white = "#cacaca"
green = "#909d63"
magenta = "#aa6292"
red = "#bc5653"
black = "#1c1c1c"
cyan = "#86d3ce"
yellow = "#ebc17a"
blue = "#7eaac7"
