[colors]
foreground = "#EBEBEB"
background = "#292C3E"
light-white = "#FEFEF8"
light-yellow = "#FFD750"
light-black = "#6D7070"
light-red = "#FF4352"
light-magenta = "#A578EA"
light-cyan = "#73FBF1"
light-green = "#B8E466"
light-blue = "#1BA6FA"
cursor = "#FF261E"
text = "#EBEBEB"
magenta = "#8763B8"
black = "#0d0d0d"
red = "#FF301B"
green = "#A0E521"
blue = "#1BA6FA"
yellow = "#FFC620"
white = "#EBEBEB"
cyan = "#21DEEF"
