[colors]
green = "#3e953a"
white = "#bbbbbb"
cyan = "#3e953a"
blue = "#2f5af3"
black = "#000000"
red = "#de3d35"
yellow = "#d2b67b"
magenta = "#a00095"
light-yellow = "#d2b67b"
light-cyan = "#3e953a"
light-magenta = "#a00095"
light-red = "#de3d35"
light-green = "#3e953a"
light-black = "#000000"
light-white = "#ffffff"
light-blue = "#2f5af3"
foreground = "#2a2b33"
background = "#f8f8f8"
