[colors]
cyan = "#90E1C6"
magenta = "#FAE994"
white = "#C7C7C7"
red = "#EA6C73"
black = "#01060E"
yellow = "#F9AF4F"
blue = "#53BDFA"
green = "#91B362"
light-blue = "#59C2FF"
light-white = "#FFFFFF"
light-magenta = "#FFEE99"
light-green = "#C2D94C"
light-black = "#686868"
light-yellow = "#FFB454"
light-cyan = "#95E6CB"
light-red = "#F07178"
foreground = "#B3B1AD"
background = "#0A0E14"
