[colors]
foreground = "#5C6166"
background = "#FCFCFC"
blue = "#4196df"
black = "#010101"
yellow = "#eba54d"
red = "#e7666a"
white = "#c1c1c1"
magenta = "#9870c3"
green = "#80ab24"
cyan = "#51b891"
light-white = "#dbdbdb"
light-black = "#343434"
light-green = "#9fd32f"
light-blue = "#6daee6"
light-red = "#ee9295"
light-magenta = "#b294d2"
light-cyan = "#75c7a8"
light-yellow = "#f0bc7b"
