[colors]
background = "#181818"
foreground = "#d8d8d8"
green = "#a1b56c"
white = "#d8d8d8"
cyan = "#86c1b9"
yellow = "#f7ca88"
black = "#181818"
red = "#ab4642"
blue = "#7cafc2"
magenta = "#ba8baf"
light-white = "#f8f8f8"
light-red = "#ab4642"
light-yellow = "#f7ca88"
light-blue = "#7cafc2"
light-cyan = "#86c1b9"
light-black = "#585858"
light-magenta = "#ba8baf"
light-green = "#a1b56c"
cursor = "#d8d8d8"
text = "#181818"
