[colors]
light-magenta = "#FF1493"
light-red = "#FF2400"
light-cyan = "#00CCCC"
light-black = "#696969"
light-white = "#FFFAFA"
light-yellow = "#FDFF00"
light-blue = "#007FFF"
light-green = "#03C03C"
yellow = "#FFD700"
blue = "#0087BD"
black = "#10100E"
red = "#C40233"
green = "#009F6B"
magenta = "#9A4EAE"
white = "#C6C6C4"
cyan = "#20B2AA"
foreground = "#C6C6C4"
background = "#10100E"
