[colors]
light-black = "#23272c"
light-green = "#59b0f2"
light-blue = "#487092"
light-yellow = "#4bb0d3"
light-magenta = "#50829e"
light-cyan = "#658795"
light-white = "#4d676b"
light-red = "#66a5cc"
background = "#2c3640"
foreground = "#297dd3"
yellow = "#2090c1"
blue = "#2c5e87"
green = "#2691e7"
black = "#0b0b0c"
cyan = "#547aa2"
white = "#536679"
red = "#377fc4"
magenta = "#436280"
