[colors]
foreground = "#fcfcfc"
light-foreground = "#ffffff"
dim-background = "#31363b"
light-background = "#000000"
dim-foreground = "#eff0f1"
background = "#232627"
red = "#ed1515"
blue = "#1d99f3"
magenta = "#9b59b6"
white = "#fcfcfc"
black = "#232627"
yellow = "#f67400"
cyan = "#1abc9c"
green = "#11d116"
light-black = "#7f8c8d"
light-blue = "#3daee9"
light-green = "#1cdc9a"
light-white = "#ffffff"
light-magenta = "#8e44ad"
light-red = "#c0392b"
light-cyan = "#16a085"
light-yellow = "#fdbc4b"
dim-white = "#63686d"
dim-black = "#31363b"
dim-yellow = "#b65619"
dim-magenta = "#614a73"
dim-cyan = "#186c60"
dim-red = "#783228"
dim-green = "#17a262"
dim-blue = "#1b668f"
