[colors]
magenta = "#881798"
green = "#13a10e"
black = "#0c0c0c"
red = "#c50f1f"
blue = "#0037da"
cyan = "#3a96dd"
white = "#cccccc"
yellow = "#c19c00"
light-black = "#767676"
light-green = "#16c60c"
light-blue = "#3b78ff"
light-white = "#f2f2f2"
light-yellow = "#f9f1a5"
light-magenta = "#b4009e"
light-red = "#e74856"
light-cyan = "#61d6d6"
background = "#0c0c0c"
foreground = "#cccccc"
