[colors]
light-cyan = "#54AFBC"
light-white = "#f7f7f7"
light-red = "#E86671"
light-magenta = "#C678DD"
light-blue = "#61AFEF"
light-yellow = "#E5C07B"
light-black = "#5C6370"
light-green = "#98C379"
white = "#ABB2BF"
magenta = "#C678DD"
green = "#98C379"
red = "#E86671"
black = "#181A1F"
yellow = "#E5C07B"
blue = "#61AFEF"
cyan = "#54AFBC"
background = "#1E1E2E"
foreground = "#d6d6d6"
text = "#CDD6F4"
cursor = "#D9D9D9"
dim-black = "#5C6370"
dim-green = "#98C379"
dim-red = "#74423f"
dim-blue = "#61AFEF"
dim-yellow = "#E5C07B"
dim-white = "#828282"
dim-magenta = "#6e4962"
dim-cyan = "#5c8482"
