[colors]
background = "#1e1c31"
foreground = "#cbe1e7"
cyan = "#63f2f1"
white = "#a6b3cc"
green = "#62d196"
yellow = "#ffb378"
magenta = "#906cff"
red = "#ff5458"
blue = "#65b2ff"
black = "#141228"
light-red = "#ff8080"
light-magenta = "#c991e1"
light-black = "#565575"
light-green = "#95ffa4"
light-yellow = "#ffe9aa"
light-blue = "#91ddff"
light-cyan = "#aaffe4"
light-white = "#cbe3e7"
cursor = "#fbfcfc"
text = "#ff271d"
