[colors]
cursor = "#008b94"
text = "#fafafa"
blue = "#539afc"
magenta = "#b62d65"
cyan = "#70e1e8"
white = "#b7c5d3"
black = "#333f4a"
green = "#8bd49c"
red = "#d95468"
light-cyan = "#70e1e8"
light-red = "#d95468"
light-blue = "#5ec4ff"
light-yellow = "#ebbf83"
light-white = "#ffffff"
light-green = "#8bd49c"
light-black = "#41505e"
light-magenta = "#e27e8d"
background = "#171d23"
foreground = "#ffffff"
