[colors]
text = "#122637"
cursor = "#f0cb09"
light-green = "#3bcf1d"
light-red = "#f40d17"
light-magenta = "#ff55ff"
light-cyan = "#6ae3f9"
light-white = "#ffffff"
light-blue = "#5555ff"
light-black = "#545454"
light-yellow = "#ecc809"
background = "#122637"
foreground = "#ffffff"
cyan = "#00bbbb"
white = "#bbbbbb"
black = "#000000"
blue = "#1460d2"
red = "#ff0000"
yellow = "#fee409"
magenta = "#ff005d"
green = "#37dd21"
