[colors]
cyan = "#0abdc6"
yellow = "#f57800"
green = "#d300c4"
blue = "#123e7c"
magenta = "#711c91"
red = "#ff0000"
white = "#d7d7d5"
black = "#123e7c"
background = "#000b1e"
foreground = "#0abdc6"
text = "#000b1e"
cursor = "#0abdc6"
light-cyan = "#0abdc6"
light-blue = "#00ff00"
light-magenta = "#711c91"
light-green = "#d300c4"
light-red = "#ff0000"
light-black = "#1c61c2"
light-yellow = "#f57800"
light-white = "#d7d7d5"
