[colors]
background = "#282a36"
foreground = "#f8f8f2"
black = "#000000"
yellow = "#f1fa8c"
red = "#ff5555"
magenta = "#ff79c6"
blue = "#caa9fa"
green = "#50fa7b"
cyan = "#8be9fd"
white = "#bfbfbf"
light-magenta = "#ff92d0"
light-green = "#5af78e"
light-blue = "#caa9fa"
light-cyan = "#9aedfe"
light-black = "#282a35"
light-yellow = "#f4f99d"
light-red = "#ff6e67"
light-white = "#e6e6e6"
