[colors]
background = "#2C2C2C"
foreground = "#DCDCCC"
green = "#60B48A"
black = "#3F3F3F"
red = "#705050"
yellow = "#DFAF8F"
white = "#DCDCCC"
magenta = "#DC8CC3"
cyan = "#8CD0D3"
blue = "#9AB8D7"
light-magenta = "#EC93D3"
light-white = "#FFFFFF"
light-blue = "#94BFF3"
light-black = "#709080"
light-red = "#DCA3A3"
light-green = "#72D5A3"
light-cyan = "#93E0E3"
light-yellow = "#F0DFAF"
