[colors]
light-black = "#555555"
light-blue = "#caa9fa"
light-yellow = "#f1fa8c"
light-red = "#ff5555"
light-white = "#ffffff"
light-magenta = "#ff79c6"
light-green = "#50fa7b"
light-cyan = "#8be9fd"
foreground = "#f8f8f2"
background = "#282a36"
white = "#bbbbbb"
magenta = "#ff79c6"
yellow = "#f1fa8c"
cyan = "#8be9fd"
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
blue = "#bd93f9"
