[colors]
foreground = "#5c6a72"
background = "#fdf6e3"
magenta = "#df69ba"
black = "#5c6a72"
red = "#f85552"
blue = "#3a94c5"
green = "#8da101"
cyan = "#35a77c"
yellow = "#dfa000"
white = "#e0dcc7"
light-black = "#5c6a72"
light-red = "#f85552"
light-magenta = "#df69ba"
light-yellow = "#dfa000"
light-green = "#8da101"
light-blue = "#3a94c5"
light-white = "#e0dcc7"
light-cyan = "#35a77c"
