[colors]
light-cyan = "#83c092"
light-white = "#d3c6aa"
light-black = "#475258"
light-red = "#e67e80"
light-yellow = "#dbbc7f"
light-green = "#a7c080"
light-magenta = "#d699b6"
light-blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
white = "#d3c6aa"
yellow = "#dbbc7f"
red = "#e67e80"
blue = "#7fbbb3"
black = "#475258"
magenta = "#d699b6"
background = "#2d353b"
foreground = "#d3c6aa"
