[colors]
light-red = "#ff8e78"
light-green = "#b1bf75"
light-blue = "#99a4bc"
light-black = "#020221"
light-white = "#f8f8ff"
light-yellow = "#ffd392"
light-cyan = "#8bccbf"
light-magenta = "#ffb07b"
background = "#020221"
foreground = "#b4b4b9"
cursor = "#ffe8c0"
text = "#020221"
black = "#000004"
green = "#718e3f"
red = "#ff3600"
blue = "#635196"
cyan = "#34bfa4"
yellow = "#ffc552"
white = "#b4b4b9"
magenta = "#ff761a"
