[colors]
light-red = "#D41919"
light-yellow = "#FEA44C"
light-green = "#5EBDAB"
light-black = "#1F2229"
light-cyan = "#49AEE6"
light-white = "#FFFFFF"
light-magenta = "#BF2E5D"
light-blue = "#367bf0"
background = "#272a34"
foreground = "#FFFFFF"
black = "#1F2229"
magenta = "#D71655"
red = "#EC0101"
yellow = "#FF8A18"
white = "#FFFFFF"
blue = "#277FFF"
green = "#47D4B9"
cyan = "#05A1F7"
