[colors]
background = "#22272e"
foreground = "#768390"
white = "#909dab"
green = "#57ab5a"
magenta = "#b083f0"
black = "#545d68"
cyan = "#39c5cf"
blue = "#539bf5"
yellow = "#c69026"
red = "#f47067"
light-black = "#636e7b"
light-magenta = "#dcbdfb"
light-green = "#6bc46d"
light-cyan = "#56d4dd"
light-white = "#cdd9e5"
light-blue = "#6cb6ff"
light-red = "#ff938a"
light-yellow = "#daaa3f"
