[colors]
light-red = "#cb2431"
light-yellow = "#b08800"
light-magenta = "#5a32a3"
light-black = "#959da5"
light-cyan = "#3192aa"
light-green = "#22863a"
light-white = "#d1d5da"
light-blue = "#005cc5"
background = "#ffffff"
foreground = "#24292f"
green = "#28a745"
cyan = "#0598bc"
magenta = "#5a32a3"
blue = "#0366d6"
white = "#6a737d"
black = "#24292e"
yellow = "#dbab09"
red = "#d73a49"
