[colors]
foreground = "#0E1116"
background = "#ffffff"
light-red = "#a40e26"
light-magenta = "#a475f9"
light-black = "#57606a"
light-blue = "#218bff"
light-cyan = "#3192aa"
light-white = "#8c959f"
light-green = "#1a7f37"
light-yellow = "#633c01"
yellow = "#4d2d00"
magenta = "#8250df"
green = "#116329"
black = "#24292f"
red = "#cf222e"
blue = "#0969da"
cyan = "#1b7c83"
white = "#6e7781"
