[colors]
light-magenta = "#b392f0"
light-yellow = "#ffea7f"
light-blue = "#79b8ff"
light-red = "#f97583"
light-white = "#fafbfc"
light-black = "#959da5"
light-cyan = "#56d4dd"
light-green = "#85e89d"
foreground = "#d1d5da"
background = "#24292e"
red = "#ea4a5a"
green = "#34d058"
yellow = "#ffea7f"
black = "#586069"
magenta = "#b392f0"
cyan = "#39c5cf"
white = "#d1d5da"
blue = "#2188ff"
