[colors]
background = "#0d1117"
foreground = "#b3b1ad"
red = "#ff7b72"
green = "#3fb950"
blue = "#58a6ff"
cyan = "#39c5cf"
yellow = "#d29922"
magenta = "#bc8cff"
white = "#b1bac4"
black = "#484f58"
light-black = "#6e7681"
light-cyan = "#56d4dd"
light-white = "#f0f6fc"
light-yellow = "#e3b341"
light-red = "#ffa198"
light-blue = "#79c0ff"
light-magenta = "#d2a8ff"
light-green = "#56d364"
