[colors]
light-blue = "#218bff"
light-green = "#1a7f37"
light-white = "#8c959f"
light-yellow = "#633c01"
light-red = "#a40e26"
light-magenta = "#a475f9"
light-cyan = "#3192aa"
light-black = "#57606a"
background = "#ffffff"
foreground = "#0E1116"
white = "#6e7781"
red = "#cf222e"
magenta = "#8250df"
yellow = "#4d2d00"
cyan = "#1b7c83"
blue = "#0969da"
black = "#24292f"
green = "#116329"
