[colors]
light-black = "#535c64"
light-green = "#33d17a"
light-red = "#f66151"
light-yellow = "#e9ad0c"
light-blue = "#2a7bde"
light-magenta = "#c061cb"
light-white = "#ffffff"
light-cyan = "#33c7de"
yellow = "#a2734c"
white = "#d0cfcc"
magenta = "#a347ba"
black = "#171421"
cyan = "#2aa1b3"
blue = "#12488b"
green = "#26a269"
red = "#c01c28"
background = "#1e1e1e"
foreground = "#ffffff"
