[colors]
background = "#0a0f14"
foreground = "#98d1ce"
light-green = "#081f2d"
light-black = "#10151b"
light-yellow = "#245361"
light-cyan = "#599caa"
light-red = "#d26939"
light-magenta = "#888ba5"
light-white = "#d3ebe9"
light-blue = "#093748"
black = "#0a0f14"
magenta = "#4e5165"
cyan = "#33859d"
yellow = "#edb54b"
red = "#c33027"
blue = "#195465"
green = "#26a98b"
white = "#98d1ce"
