[colors]
cyan = "#689d6a"
green = "#98971a"
blue = "#458588"
red = "#cc241d"
yellow = "#d79921"
black = "#282828"
magenta = "#b16286"
white = "#a89984"
background = "#282828"
foreground = "#ebdbb2"
light-cyan = "#8ec07c"
light-red = "#fb4934"
light-green = "#b8bb26"
light-yellow = "#fabd2f"
light-magenta = "#d3869b"
light-blue = "#83a598"
light-black = "#928374"
light-white = "#ebdbb2"
