[colors]
blue = "#458588"
white = "#7c6f64"
black = "#fbf1c7"
magenta = "#b16286"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
cyan = "#689d6a"
light-red = "#9d0006"
light-magenta = "#8f3f71"
light-cyan = "#427b58"
light-black = "#928374"
light-green = "#79740e"
light-yellow = "#b57614"
light-blue = "#076678"
light-white = "#3c3836"
foreground = "#3c3836"
background = "#fbf1c7"
