[colors]
blue = "#7daea3"
magenta = "#d3869b"
red = "#ea6962"
cyan = "#89b482"
black = "#665c54"
yellow = "#e78a4e"
white = "#dfbf8e"
green = "#a9b665"
background = "#282828"
foreground = "#dfbf8e"
light-green = "#a9b665"
light-blue = "#7daea3"
light-red = "#ea6962"
light-cyan = "#89b482"
light-yellow = "#e3a84e"
light-black = "#928374"
light-magenta = "#d3869b"
light-white = "#dfbf8e"
