[colors]
background = "#282433"
foreground = "#eee9fc"
light-magenta = "#e192ef"
light-cyan = "#b3f4f3"
light-green = "#b1f2a7"
light-white = "#eee9fc"
light-black = "#3f3951"
light-yellow = "#ebde76"
light-red = "#e965a5"
light-blue = "#b1baf4"
cursor = "#eee9fc"
text = "#eee9fc"
green = "#b1f2a7"
black = "#282433"
red = "#e965a5"
white = "#eee9fc"
yellow = "#ebde76"
magenta = "#e192ef"
cyan = "#b3f4f3"
blue = "#b1baf4"
