[colors]
foreground = "#dddddd"
background = "#444444"
red = "#ff0000"
blue = "#0000ff"
black = "#000000"
white = "#ffffff"
green = "#00ff00"
magenta = "#ff00ff"
yellow = "#ffff00"
cyan = "#00ffff"
text = "#aaaaaa"
cursor = "#ffffff"
light-red = "#ff0000"
light-yellow = "#ffff00"
light-green = "#00ff00"
light-blue = "#0000ff"
light-magenta = "#ff00ff"
light-black = "#000000"
light-white = "#ffffff"
light-cyan = "#00ffff"
