[colors]
cyan = "#59e1e3"
yellow = "#fab795"
black = "#16161c"
red = "#e95678"
green = "#29d398"
blue = "#26bbd9"
white = "#d5d8da"
magenta = "#ee64ac"
light-white = "#d5d8da"
light-green = "#3fdaa4"
light-red = "#ec6a88"
light-cyan = "#6be4e6"
light-black = "#5b5858"
light-magenta = "#f075b5"
light-blue = "#3fc4de"
light-yellow = "#fbc3a7"
background = "#1c1e26"
foreground = "#e0e0e0"
