[colors]
red = "#fe0100"
cyan = "#00ffff"
black = "#000000"
blue = "#0066ff"
white = "#d0d0d0"
green = "#33ff00"
yellow = "#feff00"
magenta = "#cc00ff"
text = "#F81CE5"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#000000"
light-red = "#fe0100"
light-black = "#808080"
light-cyan = "#00ffff"
light-white = "#FFFFFF"
light-blue = "#0066ff"
light-green = "#33ff00"
light-yellow = "#feff00"
light-magenta = "#cc00ff"
