[colors]
black = "#330000"
blue = "#ffcc00"
red = "#ff3300"
yellow = "#ff9900"
magenta = "#ff6600"
green = "#ff6600"
white = "#d9d9d9"
cyan = "#ff9900"
light-cyan = "#ffcc99"
light-magenta = "#ff9966"
light-blue = "#ffcc33"
light-green = "#ff9966"
light-white = "#d9d9d9"
light-black = "#663300"
light-red = "#ff6633"
light-yellow = "#ffcc99"
background = "#270d06"
foreground = "#d9d9d9"
