[colors]
background = "#101421"
foreground = "#fffbf6"
green = "#abe047"
red = "#eb4129"
magenta = "#7b5cb0"
cyan = "#64dbed"
white = "#e5e9f0"
black = "#2e2e2e"
blue = "#47a0f3"
yellow = "#f6c744"
light-yellow = "#f9da6a"
light-magenta = "#a47de9"
light-red = "#ec5357"
light-green = "#c0e17d"
light-cyan = "#99faf2"
light-white = "#ffffff"
light-blue = "#49a4f8"
light-black = "#565656"
