[colors]
foreground = "#dcd7ba"
background = "#1f1f28"
light-magenta = "#938aa9"
light-cyan = "#7aa89f"
light-white = "#dcd7ba"
light-red = "#e82424"
light-blue = "#7fb4ca"
light-green = "#98bb6c"
light-black = "#727169"
light-yellow = "#e6c384"
cyan = "#6a9589"
magenta = "#957fb8"
blue = "#7e9cd8"
black = "#090618"
red = "#c34043"
yellow = "#c0a36e"
white = "#c8c093"
green = "#76946a"
selection-background = "#2d4f67"
selection-foreground = "#c8c093"
