[colors]
light-yellow = "#E6C384"
light-red = "#E46876"
light-magenta = "#938AA9"
light-black = "#a6a69c"
light-white = "#c5c9c5"
light-cyan = "#7AA89F"
light-blue = "#7FB4CA"
light-green = "#87a987"
selection-background = "#2d4f67"
selection-foreground = "#c8c093"
yellow = "#c4b28a"
cyan = "#8ea4a2"
black = "#0d0c0c"
magenta = "#a292a3"
blue = "#8ba4b0"
green = "#8a9a7b"
red = "#c4746e"
white = "#C8C093"
background = "#181616"
foreground = "#c5c9c5"
