[colors]
cursor = "#f8f8f2"
text = "#191622"
green = "#18b218"
blue = "#1818b2"
black = "#000000"
magenta = "#b218b2"
red = "#b21818"
white = "#b2b2b2"
cyan = "#18b2b2"
yellow = "#b26818"
dim-cyan = "#18b2b2"
dim-white = "#b2b2b2"
dim-red = "#b21818"
dim-green = "#18b218"
dim-magenta = "#b218b2"
dim-blue = "#1818b2"
dim-yellow = "#b26818"
dim-black = "#000000"
light-background = "#686868"
light-foreground = "#ffffff"
background = "#1f1f1f"
dim-background = "#1f1f1f"
dim-foreground = "#e3e3e3"
foreground = "#e3e3e3"
light-red = "#ff5454"
light-black = "#686868"
light-green = "#54ff54"
light-blue = "#5454ff"
light-yellow = "#ffff54"
light-magenta = "#ff54ff"
light-white = "#ffffff"
light-cyan = "#54ffff"
