[colors]
cursor = "#ffffff"
text = "#aaaaaa"
light-yellow = "#bbbb00"
light-cyan = "#00bbbb"
light-black = "#000000"
light-red = "#bb0000"
light-blue = "#0000bb"
light-magenta = "#bb00bb"
light-white = "#bbbbbb"
light-green = "#00bb00"
yellow = "#bbbb00"
blue = "#0000bb"
black = "#000000"
magenta = "#bb00bb"
cyan = "#00bbbb"
red = "#bb0000"
white = "#bbbbbb"
green = "#00bb00"
foreground = "#dddddd"
background = "#333333"
