[colors]
text = "#ffffff"
cursor = "#fcbb6a"
light-blue = "#85add6"
light-yellow = "#fac761"
light-red = "#f97b58"
light-cyan = "#82c4c4"
light-green = "#acd1a8"
light-black = "#333333"
light-white = "#ffffff"
light-magenta = "#d8b6d8"
foreground = "#d8dee9"
background = "#343d46"
blue = "#6699cc"
white = "#f7f7f7"
cyan = "#5fb4b4"
black = "#000000"
red = "#ec5f66"
magenta = "#c695c6"
yellow = "#f9ae58"
green = "#99c794"
selection-background = "#4e5a65"
selection-text = "#d8dee9"
