[colors]
background = "#002221"
foreground = "#e6f8f8"
light-white = "#e6f6f6"
light-blue = "#4894fd"
light-magenta = "#e01dca"
light-green = "#00b6b6"
light-red = "#ea3431"
light-black = "#006562"
light-yellow = "#f8b017"
light-cyan = "#1ab2ad"
blue = "#4894fd"
black = "#002221"
yellow = "#f8b017"
magenta = "#e01dca"
green = "#00b6b6"
white = "#99dddb"
cyan = "#1ab2ad"
red = "#ea3431"
