[colors]
light-red = "#eb606b"
light-cyan = "#35434d"
light-yellow = "#f7eb95"
light-green = "#c3e88d"
light-white = "#ffffff"
light-blue = "#7dc6bf"
light-magenta = "#6c71c4"
light-black = "#a1a1a1"
white = "#ffffff"
green = "#c3e88d"
blue = "#80cbc4"
magenta = "#ff2f90"
yellow = "#f7eb95"
red = "#eb606b"
cyan = "#aeddff"
black = "#666666"
foreground = "#c4c7d1"
background = "#1e282d"
