[colors]
yellow = "#f7eb95"
magenta = "#ff2f90"
cyan = "#aeddff"
blue = "#80cbc4"
black = "#666666"
red = "#eb606b"
green = "#c3e88d"
white = "#ffffff"
light-cyan = "#35434d"
light-white = "#ffffff"
light-blue = "#7dc6bf"
light-black = "#ff262b"
light-red = "#eb606b"
light-yellow = "#f7eb95"
light-green = "#c3e88d"
light-magenta = "#6c71c4"
background = "#1e282d"
foreground = "#c4c7d1"
