[colors]
light-cyan = "#9cd8d8"
light-magenta = "#ffa1ff"
light-white = "#ffffff"
light-green = "#b3d987"
light-red = "#ff8d8d"
light-black = "#414166"
light-yellow = "#ffc57f"
light-blue = "#9bb3d3"
background = "#0c0c16"
foreground = "#d8dee9"
black = "#2c2c3d"
green = "#9ec875"
white = "#d8dee9"
cyan = "#96e0e0"
blue = "#70a7d4"
yellow = "#ffa759"
red = "#ff6e6e"
magenta = "#d291e0"
