[colors]
background = "#000000"
foreground = "#FFFFFF"
yellow = "#fa8419"
red = "#f4005f"
green = "#98e024"
cyan = "#58d1eb"
black = "#1a1a1a"
magenta = "#f4005f"
white = "#c4c5b5"
blue = "#9d65ff"
light-blue = "#9d65ff"
light-white = "#f6f6ef"
light-red = "#f4005f"
light-yellow = "#e0d561"
light-magenta = "#f4005f"
light-cyan = "#58d1eb"
light-black = "#625e4c"
light-green = "#98e024"
