[colors]
foreground = "#fff1f3"
background = "#2D2A2E"
red = "#fd6883"
green = "#adda78"
blue = "#f38d70"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#fff1f3"
yellow = "#f9cc6c"
black = "#2c2525"
light-green = "#adda78"
light-red = "#fd6883"
light-white = "#fff1f3"
light-blue = "#f38d70"
light-magenta = "#a8a9eb"
light-cyan = "#85dacc"
light-black = "#72696a"
light-yellow = "#f9cc6c"
