[colors]
background = "#1e2030"
foreground = "#7f85a3"
yellow = "#ffc777"
blue = "#3e68d7"
red = "#ff5370"
black = "#444a73"
magenta = "#fc7b7b"
cyan = "#86e1fc"
green = "#4fd6be"
white = "#d0d0d0"
light-cyan = "#b4f9f8"
light-white = "#5f8787"
light-green = "#c3e88d"
light-black = "#828bb8"
light-yellow = "#ffc777"
light-magenta = "#ff966c"
light-red = "#ff98a4"
light-blue = "#82aaff"
cursor = "#808080"
text = "#7f85a3"
