[colors]
magenta = "#403f53"
green = "#2aa298"
cyan = "#08916a"
red = "#d3423e"
white = "#7a8181"
black = "#011627"
blue = "#4876d6"
yellow = "#daaa01"
selection-background = "#f2f2f2"
selection-text = "#403f53"
cursor = "#403f53"
text = "#fbfbfb"
background = "#ffffff"
foreground = "#403f53"
light-blue = "#5ca7e4"
light-red = "#f76e6e"
light-black = "#7a8181"
light-cyan = "#00c990"
light-yellow = "#dac26b"
light-magenta = "#697098"
light-green = "#49d0c5"
light-white = "#989fb1"
