[colors]
blue = "#719cd6"
magenta = "#9d79d6"
red = "#c94f6d"
green = "#81b29a"
white = "#dfdfe0"
cyan = "#63cdcf"
yellow = "#dbc074"
black = "#393b44"
light-white = "#e4e4e5"
light-green = "#8ebaa4"
light-black = "#575860"
light-magenta = "#baa1e2"
light-cyan = "#7ad5d6"
light-yellow = "#e0c989"
light-blue = "#86abdc"
light-red = "#d16983"
foreground = "#cdcecf"
background = "#192330"
