[colors]
red = "#BF616A"
white = "#E5E9F0"
green = "#A3BE8C"
cyan = "#88C0D0"
black = "#3B4252"
magenta = "#B48EAD"
yellow = "#EBCB8B"
blue = "#81A1C1"
foreground = "#D8DEE9"
background = "#2E3440"
light-green = "#A3BE8C"
light-magenta = "#B48EAD"
light-blue = "#81A1C1"
light-black = "#4C566A"
light-white = "#ECEFF4"
light-red = "#BF616A"
light-yellow = "#EBCB8B"
light-cyan = "#8FBCBB"
