[colors]
foreground = "#d8dee9"
background = "#1b2b34"
blue = "#6699cc"
magenta = "#c594c5"
cyan = "#5fb3b3"
black = "#29414f"
green = "#99c794"
yellow = "#fac863"
white = "#65737e"
red = "#ec5f67"
light-green = "#99c794"
light-yellow = "#fac863"
light-red = "#ec5f67"
light-magenta = "#c594c5"
light-blue = "#6699cc"
light-black = "#405860"
light-white = "#adb5c0"
light-cyan = "#5fb3b3"
