[colors]
white = "#bfbfbf"
cyan = "#8d79ba"
green = "#50fa7b"
blue = "#bd93f9"
black = "#000000"
red = "#ff5555"
yellow = "#effa78"
magenta = "#ff79c6"
cursor = "#f8f8f2"
text = "#191622"
light-black = "#4d4d4d"
light-cyan = "#aa91e3"
light-magenta = "#ff92d0"
light-white = "#e6e6e6"
light-red = "#ff6e67"
light-green = "#5af78e"
light-blue = "#caa9fa"
light-yellow = "#eaf08d"
dim-red = "#a90000"
dim-white = "#5f5f5f"
dim-blue = "#530aba"
dim-magenta = "#bb006b"
dim-cyan = "#433364"
dim-black = "#000000"
dim-yellow = "#a3b106"
dim-green = "#049f2b"
foreground = "#e1e1e6"
background = "#191622"
