[colors]
background = "#1e2127"
foreground = "#abb2bf"
magenta = "#c678dd"
cyan = "#56b6c2"
yellow = "#d19a66"
white = "#abb2bf"
blue = "#61afef"
black = "#1e2127"
red = "#e06c75"
green = "#98c379"
light-white = "#ffffff"
light-black = "#5c6370"
light-yellow = "#d19a66"
light-red = "#e06c75"
light-magenta = "#c678dd"
light-blue = "#61afef"
light-green = "#98c379"
light-cyan = "#56b6c2"
