[colors]
light-white = "#ffffff"
light-cyan = "#a3f7ff"
light-blue = "#9cc4ff"
light-green = "#ddffa7"
light-black = "#434758"
light-red = "#ff8b92"
light-magenta = "#e1acff"
light-yellow = "#ffe585"
cyan = "#89ddff"
red = "#f07178"
green = "#c3e88d"
magenta = "#c792ea"
yellow = "#ffcb6b"
blue = "#82aaff"
white = "#d0d0d0"
black = "#292d3e"
background = "#292d3e"
foreground = "#d0d0d0"
