[colors]
text = "#1c1c1c"
cursor = "#808080"
black = "#1c1c1c"
yellow = "#d7af5f"
red = "#af005f"
magenta = "#808080"
white = "#d0d0d0"
cyan = "#d7875f"
green = "#5faf00"
blue = "#5fafd7"
background = "#1c1c1c"
foreground = "#808080"
light-blue = "#ffaf00"
light-red = "#5faf5f"
light-cyan = "#00afaf"
light-yellow = "#af87d7"
light-black = "#585858"
light-magenta = "#ffaf00"
light-white = "#5f8787"
light-green = "#afd700"
