[colors]
foreground = "#000000"
background = "#F2EEDE"
light-magenta = "#5C21A5"
light-cyan = "#158C86"
light-blue = "#1E6FCC"
light-black = "#555555"
light-red = "#CC3E28"
light-white = "#AAAAAA"
light-yellow = "#B58900"
light-green = "#216609"
blue = "#1E6FCC"
green = "#216609"
cyan = "#158C86"
black = "#000000"
red = "#CC3E28"
white = "#AAAAAA"
magenta = "#5C21A5"
yellow = "#B58900"
