[colors]
background = "#eeeeee"
foreground = "#444444"
cursor = "#444444"
text = "#eeeeee"
light-white = "#005f87"
light-yellow = "#8700af"
light-black = "#bcbcbc"
light-red = "#d70000"
light-green = "#d70087"
light-magenta = "#d75f00"
light-blue = "#d75f00"
light-cyan = "#005faf"
black = "#eeeeee"
white = "#444444"
cyan = "#005f87"
red = "#af0000"
magenta = "#878787"
blue = "#0087af"
green = "#008700"
yellow = "#5f8700"
