[colors]
magenta = "#523c79"
white = "#e0e0e0"
black = "#212121"
green = "#10a778"
yellow = "#a89c14"
blue = "#008ec4"
red = "#c30771"
cyan = "#20a5ba"
light-white = "#f1f1f1"
light-cyan = "#4fb8cc"
light-yellow = "#f3e430"
light-black = "#212121"
light-green = "#5fd7af"
light-red = "#fb007a"
light-magenta = "#6855de"
light-blue = "#20bbfc"
foreground = "#424242"
background = "#f1f1f1"
