[colors]
background = "#212121"
foreground = "#f1f1f1"
yellow = "#a89c14"
red = "#c30771"
black = "#212121"
magenta = "#523c79"
cyan = "#20a5ba"
green = "#10a778"
blue = "#008ec4"
white = "#e0e0e0"
light-blue = "#20bbfc"
light-magenta = "#6855de"
light-red = "#fb007a"
light-black = "#818181"
light-white = "#f1f1f1"
light-green = "#5fd7af"
light-cyan = "#4fb8cc"
light-yellow = "#f3e430"
