[colors]
foreground = "#AADA4F"
background = "#192835"
light-green = "#2286b5"
light-magenta = "#c6c842"
light-cyan = "#8a5135"
light-blue = "#93ca5b"
light-black = "#5B4375"
light-yellow = "#5ab782"
light-red = "#426bb6"
light-white = "#c54646"
black = "#5B4375"
green = "#2286b5"
blue = "#93ca5b"
magenta = "#c6c842"
red = "#426bb6"
yellow = "#5ab782"
white = "#c54646"
cyan = "#8a5135"
