[colors]
foreground = "#f9e7c4"
light-foreground = "#1C1508"
dim-background = "#202322"
light-background = "#353433"
background = "#2c2b2a"
dim-foreground = "#685E4A"
text = "#f9e7c4"
cursor = "#f9e7c4"
green = "#8c9440"
cyan = "#5e8d87"
blue = "#5f819d"
red = "#a54242"
yellow = "#de935f"
black = "#282a2e"
magenta = "#85678f"
white = "#707880"
orange = "#cc6953"
light-black = "#373b41"
light-yellow = "#f0c674"
light-red = "#cc6666"
light-magenta = "#b294bb"
light-green = "#b5bd68"
light-cyan = "#8abeb7"
light-white = "#c5c8c6"
light-blue = "#81a2be"
