[colors]
text = "#e0def4"
cursor = "#524f67"
line_indicator-background = "None"
line_indicator-foreground = "None"
white = "#e0def4"
magenta = "#c4a7e7"
red = "#eb6f92"
cyan = "#ebbcba"
black = "#26233a"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
selection-text = "#e0def4"
selection-background = "#403d52"
light-blue = "#9ccfd8"
light-red = "#eb6f92"
light-black = "#6e6a86"
light-yellow = "#f6c177"
light-magenta = "#c4a7e7"
light-cyan = "#ebbcba"
light-white = "#e0def4"
light-green = "#31748f"
vi_mode_cursor-text = "#e0def4"
vi_mode_cursor-cursor = "#524f67"
foreground = "#e0def4"
background = "#191724"
