[colors]
line_indicator-foreground = "None"
line_indicator-background = "None"
foreground = "#575279"
background = "#faf4ed"
cursor = "#cecacd"
text = "#575279"
vi_mode_cursor-text = "#575279"
vi_mode_cursor-cursor = "#cecacd"
selection-background = "#dfdad9"
selection-text = "#575279"
red = "#b4637a"
magenta = "#907aa9"
black = "#f2e9e1"
cyan = "#d7827e"
yellow = "#ea9d34"
green = "#286983"
white = "#575279"
blue = "#56949f"
light-magenta = "#907aa9"
light-cyan = "#d7827e"
light-white = "#575279"
light-blue = "#56949f"
light-red = "#b4637a"
light-black = "#9893a5"
light-green = "#286983"
light-yellow = "#ea9d34"
