[colors]
white = "#e0def4"
magenta = "#c4a7e7"
cyan = "#ea9a97"
blue = "#9ccfd8"
yellow = "#f6c177"
red = "#eb6f92"
black = "#393552"
green = "#3e8fb0"
cursor = "#56526e"
text = "#e0def4"
line_indicator-foreground = "None"
line_indicator-background = "None"
selection-background = "#44415a"
selection-text = "#e0def4"
light-cyan = "#ea9a97"
light-green = "#3e8fb0"
light-black = "#6e6a86"
light-yellow = "#f6c177"
light-red = "#eb6f92"
light-white = "#e0def4"
light-blue = "#9ccfd8"
light-magenta = "#c4a7e7"
background = "#232136"
foreground = "#e0def4"
vi_mode_cursor-cursor = "#56526e"
vi_mode_cursor-text = "#e0def4"
