[colors]
text = "#061822"
cursor = "#feaf3c"
light-blue = "#0bc7e3"
light-yellow = "#fedaae"
light-magenta = "#c6e8f1"
light-green = "#739da8"
light-red = "#dd998a"
light-white = "#ffe9d7"
light-black = "#545d65"
light-cyan = "#97b9c0"
selection-background = "#265b75"
selection-text = "#ffe9d7"
background = "#061923"
foreground = "#e5c49e"
red = "#db662d"
green = "#008eab"
cyan = "#5fb1c2"
magenta = "#77dbf4"
white = "#e5c49e"
yellow = "#feaf3c"
blue = "#255a62"
black = "#1d485f"
