[colors]
text = "#000000"
cursor = "#fefffe"
selection-background = "#b3d7ff"
selection-text = "#000000"
foreground = "#dbdbdb"
background = "#14191e"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#bf3fbd"
yellow = "#c7c400"
black = "#14191e"
red = "#b43c29"
blue = "#2743c7"
white = "#c7c7c7"
light-red = "#dc7974"
light-yellow = "#ece100"
light-green = "#57e690"
light-blue = "#a6aaf1"
light-magenta = "#e07de0"
light-white = "#feffff"
light-cyan = "#5ffdff"
light-black = "#676767"
