[colors]
light-black = "#686868"
light-blue = "#57c7ff"
light-red = "#ff5c57"
light-magenta = "#ff6ac1"
light-white = "#f1f1f0"
light-yellow = "#f3f99d"
light-cyan = "#9aedfe"
light-green = "#5af78e"
yellow = "#f3f99d"
red = "#ff5c57"
cyan = "#9aedfe"
black = "#282a36"
green = "#5af78e"
blue = "#57c7ff"
magenta = "#ff6ac1"
white = "#f1f1f0"
background = "#282a36"
foreground = "#eff0eb"
