[colors]
foreground = "#586e75"
background = "#fdf6e3"
black = "#073642"
cyan = "#2aa198"
yellow = "#b58900"
white = "#eee8d5"
blue = "#268bd2"
red = "#dc322f"
green = "#859900"
magenta = "#d33682"
light-blue = "#839496"
light-white = "#fdf6e3"
light-yellow = "#657b83"
light-magenta = "#6c71c4"
light-black = "#002b36"
light-red = "#cb4b16"
light-green = "#586e75"
light-cyan = "#93a1a1"
