[colors]
red = "#dc322f"
black = "#073642"
blue = "#268bd2"
white = "#eee8d5"
magenta = "#d33682"
green = "#859900"
yellow = "#b58900"
cyan = "#2aa198"
foreground = "#839496"
background = "#002b36"
light-magenta = "#6c71c4"
light-cyan = "#93a1a1"
light-blue = "#839496"
light-green = "#586e75"
light-white = "#fdf6e3"
light-black = "#002b36"
light-yellow = "#657b83"
light-red = "#cb4b16"
