[colors]
blue = "#8bbce5"
black = "#26282a"
cyan = "#a2e1f8"
white = "#f1f1f1"
yellow = "#fffcb7"
magenta = "#ffb2fe"
green = "#b4fb73"
red = "#ff8878"
foreground = "#f0f0f0"
background = "#26282a"
foreground = "#26282a"
background = "#f0f0f0"
light-red = "#fe978b"
light-white = "#ffffff"
light-yellow = "#fffed5"
light-cyan = "#c0e9f8"
light-green = "#d6fcba"
light-black = "#6f6f6f"
light-blue = "#c2e3ff"
light-magenta = "#ffc6ff"
