[colors]
green = "#4e9a06"
yellow = "#c4a000"
red = "#cc0000"
black = "#2e3436"
blue = "#3465a4"
white = "#d3d7cf"
magenta = "#75507b"
cyan = "#06989a"
light-yellow = "#fce94f"
light-red = "#ef2929"
light-blue = "#729fcf"
light-black = "#555753"
light-green = "#8ae234"
light-cyan = "#34e2e2"
light-magenta = "#ad7fa8"
light-white = "#eeeeec"
foreground = "#d3d7cf"
background = "#2e3436"
