[colors]
light-red = "#f43753"
light-black = "#4c4c4c"
light-green = "#c9d05c"
light-blue = "#b3deef"
light-yellow = "#ffc24b"
light-magenta = "#d3b987"
light-cyan = "#73cef4"
light-white = "#feffff"
background = "#282828"
foreground = "#eeeeee"
blue = "#b3deef"
red = "#f43753"
yellow = "#ffc24b"
green = "#c9d05c"
magenta = "#d3b987"
black = "#282828"
cyan = "#73cef4"
white = "#eeeeee"
