[colors]
red = "#990000"
green = "#00a600"
yellow = "#999900"
white = "#bfbfbf"
cyan = "#00a6b2"
blue = "#0000b2"
black = "#000000"
magenta = "#b200b2"
light-green = "#00d900"
light-red = "#e50000"
light-white = "#e5e5e5"
light-cyan = "#00e5e5"
light-yellow = "#e5e500"
light-black = "#666666"
light-blue = "#0000ff"
light-magenta = "#e500e5"
background = "#000000"
foreground = "#b6b6b6"
