[colors]
background = "#1D1F28"
foreground = "#FDFDFD"
yellow = "#F2A272"
green = "#5ADECD"
white = "#FDFDFD"
red = "#F37F97"
magenta = "#C574DD"
blue = "#8897F4"
cyan = "#79E6F3"
black = "#282A36"
light-cyan = "#3FDCEE"
light-blue = "#FF8037"
light-yellow = "#EBCB8B"
light-black = "#414458"
light-white = "#BEBEC1"
light-magenta = "#556FFF"
light-red = "#FF4971"
light-green = "#18E3C8"
