[colors]
foreground = "#a9b1d6"
background = "#24283b"
light-magenta = "#bb9af7"
light-yellow = "#ff9e64"
light-blue = "#7da6ff"
light-cyan = "#0db9d7"
light-white = "#acb0d0"
light-red = "#ff7a93"
light-black = "#444b6a"
light-green = "#b9f27c"
magenta = "#ad8ee6"
green = "#9ece6a"
cyan = "#449dab"
white = "#9699a8"
red = "#f7768e"
black = "#32344a"
blue = "#7aa2f7"
yellow = "#e0af68"
