[colors]
light-blue = "#7da6ff"
light-green = "#b9f27c"
light-cyan = "#0db9d7"
light-red = "#ff7a93"
light-black = "#444b6a"
light-yellow = "#ff9e64"
light-magenta = "#bb9af7"
light-white = "#acb0d0"
foreground = "#a9b1d6"
background = "#1a1b26"
blue = "#7aa2f7"
red = "#f7768e"
white = "#787c99"
black = "#32344a"
yellow = "#e0af68"
green = "#9ece6a"
magenta = "#ad8ee6"
cyan = "#449dab"
