[colors]
background = "#1d1f21"
foreground = "#c5c8c6"
text = "#1d1f21"
cursor = "#ffffff"
cyan = "#70c0ba"
red = "#cc6666"
magenta = "#b294bb"
black = "#1d1f21"
blue = "#81a2be"
white = "#373b41"
yellow = "#e6c547"
green = "#b5bd68"
light-green = "#9ec400"
light-yellow = "#f0c674"
light-red = "#ff3334"
light-cyan = "#54ced6"
light-white = "#282a2e"
light-magenta = "#b77ee0"
light-blue = "#81a2be"
light-black = "#666666"
