[colors]
background = "#000000"
foreground = "#eaeaea"
white = "#424242"
blue = "#7aa6da"
black = "#000000"
yellow = "#e6c547"
red = "#d54e53"
magenta = "#c397d8"
green = "#b9ca4a"
cyan = "#70c0ba"
light-magenta = "#b77ee0"
light-red = "#ff3334"
light-green = "#9ec400"
light-black = "#666666"
light-yellow = "#e7c547"
light-blue = "#7aa6da"
light-cyan = "#54ced6"
light-white = "#2a2a2a"
