[colors]
light-black = "#555753"
light-blue = "#729fcf"
light-yellow = "#fce94f"
light-magenta = "#ad7fa8"
light-green = "#8ae234"
light-cyan = "#34e2e2"
light-white = "#eeeeec"
light-red = "#ef2929"
background = "#300a24"
foreground = "#eeeeec"
text = "#bbbbbb"
cursor = "#b4d5ff"
white = "#d3d7cf"
red = "#cc0000"
blue = "#3465a4"
black = "#2e3436"
cyan = "#06989a"
green = "#4e9a06"
yellow = "#c4a000"
magenta = "#75507b"
