[colors]
light-green = "#e3f7a1"
light-yellow = "#f2e9bf"
light-red = "#f99f92"
light-white = "#ffffff"
light-blue = "#b3d2ff"
light-black = "#b4b4b4"
light-cyan = "#c2fefa"
light-magenta = "#e5bdff"
yellow = "#efdfac"
black = "#000000"
blue = "#6ebaf8"
red = "#f7786d"
magenta = "#ef88ff"
cyan = "#90fdf8"
white = "#e5e1d8"
green = "#bde97c"
foreground = "#e5e1d8"
background = "#1f1f1f"
