[colors]
foreground = "#ffffff"
background = "#000000"
white = "#e5e5e5"
magenta = "#cd00cd"
cyan = "#00cdcd"
blue = "#0000ee"
black = "#000000"
yellow = "#cdcd00"
green = "#00cd00"
red = "#cd0000"
light-cyan = "#00ffff"
light-green = "#00ff00"
light-white = "#ffffff"
light-magenta = "#ff00ff"
light-red = "#ff0000"
light-black = "#7f7f7f"
light-yellow = "#ffff00"
light-blue = "#5c5cff"
