[colors]
light-green = "#C3BF9F"
light-blue = "#94BFF3"
light-black = "#709080"
light-cyan = "#93E0E3"
light-yellow = "#F0DFAF"
light-red = "#DCA3A3"
light-magenta = "#EC93D3"
light-white = "#FFFFFF"
background = "#3A3A3A"
foreground = "#DCDCCC"
green = "#60B48A"
white = "#DCDCCC"
blue = "#506070"
red = "#D78787"
black = "#1E2320"
yellow = "#DFAF8F"
magenta = "#DC8CC3"
cyan = "#8CD0D3"
